[package]
name = "backend"
version = "0.0.0"
edition = "2021"

[lib]
name = "backend"

[dependencies]
axum = "0.5"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
tokio = { version = "1", features = ["full"] }
